buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/maven' }
        maven {
            url "https://repo.spongepowered.org/repository/maven-public/"
            content { includeGroup "org.spongepowered" }
        }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.0.+', changing: true
        classpath 'org.parchmentmc:librarian:1.+'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id "idea"
    id "java"
    id 'eclipse'
    id 'maven-publish'
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'org.spongepowered.mixin'

base {
    archivesName.set("DeReMetallica-FORGE-$minecraftVersion")
    group = "com.drunkmare"
    version = modVersion
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: mappingsChannel, version: mappingsVersion

    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")

    runs {
        client {
            workingDirectory project.file('run/client')

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            arg "-mixin.config=de_re_metallica.mixins.json"

            mods {
                de_re_metallica {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run/server')

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            arg "-mixin.config=de_re_metallica.mixins.json"

            mods {
                de_re_metallica {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            args '--mod', 'de_re_metallica', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            arg "-mixin.config=de_re_metallica.mixins.json"

            mods {
                de_re_metallica {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        // TFC and Create via CurseMaven
        url = 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = 'https://jitpack.io' } // Mixin Extras
    maven { // Patchouli
        name = "BlameJared"
        url = "https://maven.blamejared.com"
    }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    minecraft("net.minecraftforge:forge:$minecraftVersion-$forgeVersion")

    // Mixin
    annotationProcessor "org.spongepowered:mixin:$mixinVersion:processor"

    // TFC
    implementation fg.deobf("curse.maven:terrafirmacraft-302973:$tfcFileID")

    // Create
    implementation fg.deobf("curse.maven:create-328085:$createFileID")

    // AlekiShips
    implementation fg.deobf("curse.maven:alekiships-1068445:5963449")

    // Patchouli (required by TFC at runtime)
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-81-FORGE")
}

mixin {
    add sourceSets.main, 'de_re_metallica.refmap.json'
}

jar {
    manifest {
        attributes(["Specification-Title"     : "de_re_metallica",
                    "Specification-Vendor"    : "Drunkmare",
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : "Drunkmare",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    "TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
                    "TweakOrder"              : 0,
                    "MixinConfigs"            : "de_re_metallica.mixins.json"])
    }
}

idea {
    module {
        excludeDirs.add(file("run"))
        downloadJavadoc = true
        downloadSources = true
    }
}

jar.finalizedBy('reobfJar')

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            artifact jar
            artifact sourcesJar
        }
    }
    repositories {
        maven { url = "file://${project.projectDir}/mcmodsrepo" }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
