# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:\\Users\\Elliot\\.gradle\\jdks\\eclipse_adoptium-17-amd64-windows\\jdk-17.0.18+8
org.gradle.daemon=false
# Mod stuff
modID=de_re_metallica
modVersion=1.0.0
# Minecraft stuff
minecraftVersion=1.20.1
# Mappings
mappingsChannel=parchment
mappingsVersion=2023.09.03-1.20.1
# Forge stuff
forgeVersion=47.1.3
# Dependency things
mixinVersion=0.8.5
mixinextrasVersion=0.3.5
tfcFileID=5478226
createFileID=5838779
# AlekiShips - place the alekiships jar in libs/alekiships.jar
# or update this to reference a published version
