TFC_WOODS: dict[str, str] = {"acacia": "Acacia",
                             "ash": "Ash",
                             "aspen": "Aspen",
                             "birch": "Birch",
                             "blackwood": "Blackwood",
                             "chestnut": "Chestnut",
                             "douglas_fir": "Douglas Fir",
                             "hickory": "Hickory",
                             "kapok": "Kapok",
                             "mangrove": "Mangrove",
                             "maple": "Maple",
                             "oak": "Oak",
                             "palm": "Palm",
                             "pine": "Pine",
                             "rosewood": "Rosewood",
                             "sequoia": "Sequoia",
                             "spruce": "Spruce",
                             "sycamore": "Sycamore",
                             "white_cedar": "White Cedar",
                             "willow": "Willow"}

COLORS = ["white",
          "orange",
          "magenta",
          "light_blue",
          "yellow",
          "lime",
          "pink",
          "gray",
          "light_gray",
          "cyan",
          "purple",
          "blue",
          "brown",
          "green",
          "red",
          "black"]

FLORAE_WOODS: dict[str, str] = {"african_padauk": "African Padauk",
                                "alder": "Alder",
                                "angelim": "Angelim",
                                "argyle_eucalyptus": "Argyle Eucalyptus",
                                "bald_cypress": "Bald Cypress",
                                # TODO fill out the empty strings to be translation key version of the wood name
                                "baobab": "",
                                "beech": "",
                                "black_walnut": "",
                                "black_willow": "",
                                "brazilwood": "",
                                "butternut": "",
                                "buxus": "",
                                "cocobolo": "",
                                "common_oak": "",
                                "cypress": "",
                                "ebony": "",
                                "fever": "",
                                "ghaf": "",
                                "ginkgo": "",
                                "greenheart": "",
                                "hawthorn": "",
                                "hazel": "",
                                "hemlock": "",
                                "holly": "",
                                "hornbeam": "",
                                "iroko": "",
                                "ironwood": "",
                                "jabuticabeira": "",
                                "joshua": "",
                                "juniper": "",
                                "kauri": "",
                                "larch": "",
                                "laurel": "",
                                "limba": "",
                                "locust": "",
                                "logwood": "",
                                "maclura": "",
                                "mahoe": "",
                                "mahogany": "",
                                "marblewood": "",
                                "medlar": "",
                                "messmate": "",
                                "mountain_ash": "",
                                "mulberry": "",
                                "nordmann_fir": "",
                                "norway_spruce": "",
                                "pear": "",
                                "pink_cherry_blossom": "",
                                "pink_ipe": "",
                                "pink_ivory": "",
                                "poplar": "",
                                "purple_ipe": "",
                                "purple_jacaranda": "",
                                "purpleheart": "",
                                "quince": "",
                                "rainbow_eucalyptus": "",
                                "red_cedar": "",
                                "red_cypress": "",
                                "red_elm": "",
                                "red_mangrove": "",
                                "redwood": "",
                                "rowan": "",
                                "rubber_fig": "",
                                "sloe": "",
                                "snow_gum_eucalyptus": "",
                                "sorb": "",
                                "sweetgum": "",
                                "syzygium": "",
                                "teak": "",
                                "walnut": "",
                                "wenge": "",
                                "white_cherry_blossom": "",
                                "white_elm": "",
                                "white_ipe": "",
                                "white_jacaranda": "",
                                "white_mangrove": "",
                                "whitebeam": "",
                                "yellow_ipe": "",
                                "yellow_jacaranda": "",
                                "yellow_meranti": "",
                                "yew": "",
                                "zebrawood": "",
                                "persimmon": "",
                                "bamboo": ""}

DEFAULT_LANG = {

    "item.alekiships.testitem": "They're waiting for you, Mr. Freeman. With the Test Item.",

    "entity.alekiships.dugout_canoe.acacia": "Acacia Dugout Canoe",
    "entity.alekiships.dugout_canoe.ash": "Ash Dugout Canoe",
    "entity.alekiships.dugout_canoe.aspen": "Aspen Dugout Canoe",
    "entity.alekiships.dugout_canoe.birch": "Birch Dugout Canoe",
    "entity.alekiships.dugout_canoe.blackwood": "Blackwood Dugout Canoe",
    "entity.alekiships.dugout_canoe.chestnut": "Chestnut Dugout Canoe",
    "entity.alekiships.dugout_canoe.douglas_fir": "Douglas Fir Dugout Canoe",
    "entity.alekiships.dugout_canoe.hickory": "Hickory Dugout Canoe",
    "entity.alekiships.dugout_canoe.kapok": "Kapok Dugout Canoe",
    "entity.alekiships.dugout_canoe.maple": "Maple Dugout Canoe",
    "entity.alekiships.dugout_canoe.oak": "Oak Dugout Canoe",
    "entity.alekiships.dugout_canoe.palm": "Palm Dugout Canoe",
    "entity.alekiships.dugout_canoe.pine": "Pine Dugout Canoe",
    "entity.alekiships.dugout_canoe.rosewood": "Rosewood Dugout Canoe",
    "entity.alekiships.dugout_canoe.sequoia": "Sequoia Dugout Canoe",
    "entity.alekiships.dugout_canoe.spruce": "Spruce Dugout Canoe",
    "entity.alekiships.dugout_canoe.sycamore": "Sycamore Dugout Canoe",
    "entity.alekiships.dugout_canoe.white_cedar": "White Cedar Dugout Canoe",
    "entity.alekiships.dugout_canoe.willow": "Willow Dugout Canoe",

    "entity.alekiships.rowboat.acacia": "Acacia Rowboat",
    "entity.alekiships.rowboat.ash": "Ash Rowboat",
    "entity.alekiships.rowboat.aspen": "Aspen Rowboat",
    "entity.alekiships.rowboat.birch": "Birch Rowboat",
    "entity.alekiships.rowboat.blackwood": "Blackwood Rowboat",
    "entity.alekiships.rowboat.chestnut": "Chestnut Rowboat",
    "entity.alekiships.rowboat.douglas_fir": "Douglas Fir Rowboat",
    "entity.alekiships.rowboat.hickory": "Hickory Rowboat",
    "entity.alekiships.rowboat.kapok": "KapokRowboat",
    "entity.alekiships.rowboat.maple": "Maple Rowboat",
    "entity.alekiships.rowboat.oak": "Oak Rowboat",
    "entity.alekiships.rowboat.palm": "Palm Rowboat",
    "entity.alekiships.rowboat.pine": "Pine Rowboat",
    "entity.alekiships.rowboat.rosewood": "Rosewood Rowboat",
    "entity.alekiships.rowboat.sequoia": "Sequoia Rowboat",
    "entity.alekiships.rowboat.spruce": "Spruce Rowboat",
    "entity.alekiships.rowboat.sycamore": "Sycamore Rowboat",
    "entity.alekiships.rowboat.white_cedar": "White Cedar Rowboat",
    "entity.alekiships.rowboat.willow": "Willow Rowboat",

    "entity.alekiships.sloop.acacia": "Acacia Sloop",
    "entity.alekiships.sloop.ash": "Ash Sloop",
    "entity.alekiships.sloop.aspen": "Aspen Sloop",
    "entity.alekiships.sloop.birch": "Birch Sloop",
    "entity.alekiships.sloop.blackwood": "Blackwood Sloop",
    "entity.alekiships.sloop.chestnut": "Chestnut Sloop",
    "entity.alekiships.sloop.douglas_fir": "Douglas Fir Sloop",
    "entity.alekiships.sloop.hickory": "Hickory Sloop",
    "entity.alekiships.sloop.kapok": "KapokRowboat",
    "entity.alekiships.sloop.maple": "Maple Sloop",
    "entity.alekiships.sloop.oak": "Oak Sloop",
    "entity.alekiships.sloop.palm": "Palm Sloop",
    "entity.alekiships.sloop.pine": "Pine Sloop",
    "entity.alekiships.sloop.rosewood": "Rosewood Sloop",
    "entity.alekiships.sloop.sequoia": "Sequoia Sloop",
    "entity.alekiships.sloop.spruce": "Spruce Sloop",
    "entity.alekiships.sloop.sycamore": "Sycamore Sloop",
    "entity.alekiships.sloop.white_cedar": "White Cedar Sloop",
    "entity.alekiships.sloop.willow": "Willow Sloop",

    "entity.alekiships.sloop_construction.acacia": "Acacia Sloop",
    "entity.alekiships.sloop_construction.ash": "Ash Sloop",
    "entity.alekiships.sloop_construction.aspen": "Aspen Sloop",
    "entity.alekiships.sloop_construction.birch": "Birch Sloop",
    "entity.alekiships.sloop_construction.blackwood": "Blackwood Sloop",
    "entity.alekiships.sloop_construction.chestnut": "Chestnut Sloop",
    "entity.alekiships.sloop_construction.douglas_fir": "Douglas Fir Sloop",
    "entity.alekiships.sloop_construction.hickory": "Hickory Sloop",
    "entity.alekiships.sloop_construction.kapok": "KapokRowboat",
    "entity.alekiships.sloop_construction.maple": "Maple Sloop",
    "entity.alekiships.sloop_construction.oak": "Oak Sloop",
    "entity.alekiships.sloop_construction.palm": "Palm Sloop",
    "entity.alekiships.sloop_construction.pine": "Pine Sloop",
    "entity.alekiships.sloop_construction.rosewood": "Rosewood Sloop",
    "entity.alekiships.sloop_construction.sequoia": "Sequoia Sloop",
    "entity.alekiships.sloop_construction.spruce": "Spruce Sloop",
    "entity.alekiships.sloop_construction.sycamore": "Sycamore Sloop",
    "entity.alekiships.sloop_construction.white_cedar": "White Cedar Sloop",
    "entity.alekiships.sloop_construction.willow": "Willow Sloop",

    "entity.alekiships.kayak": "Kayak",

    "entity.alekiships.vehicle_part": "Vehicle Part",
    "entity.alekiships.vehicle_cleat": "Cleat",
    "entity.alekiships.vehicle_switch_windlass": "Windlass",
    "entity.alekiships.vehicle_switch_sail": "Sail",
    "entity.alekiships.vehicle_collider": "Vehicle",
    "entity.alekiships.vehicle_part_boat": "Boat Part",
    "entity.alekiships.vehicle_mast": "Mast",

    "entity.alekiships.cannonball": "Cannonball",
    "entity.alekiships.cannon": "Cannon",

    # Compartments
    "entity.alekiships.compartment_empty": "Empty Compartment",
    "entity.alekiships.compartment_barrel": "Barrel Compartment",
    "entity.alekiships.compartment_chest": "Chest Compartment",
    "entity.alekiships.compartment_ender_chest": "Ender Chest Compartment",
    "entity.alekiships.compartment_shulker_box": "Shulker Box Compartment",
    "entity.alekiships.compartment_furnace": "Furnace Compartment",
    "entity.alekiships.compartment_blast_furnace": "Blast Furnace Compartment",
    "entity.alekiships.compartment_smoker": "Smoker Compartment",
    "entity.alekiships.compartment_brewing_stand": "Brewing Stand Compartment",
    "entity.alekiships.compartment_crafting_table": "Workbench Compartment",
    "entity.alekiships.compartment_stonecutter": "Stonecutter Compartment",
    "entity.alekiships.compartment_cartography_table": "Cartography Table Compartment",
    "entity.alekiships.compartment_smithing_table": "Smithing Table Compartment",
    "entity.alekiships.compartment_grindstone": "Grindstone Compartment",
    "entity.alekiships.compartment_loom": "Loom Compartment",

    "block.alekiships.boat_frame": "Shipwright's Scaffolding",

    "block.alekiships.thatch_roofing": "Thatch Roofing",

    "itemGroup.alekiships": "aleki's Nifty Ships",
    "creativetab.alekiships_tab": "aleki's Nifty Ships",
    "creativetab.watercraft_tab": "Watercraft",
    "creativetab.navigation_tab": "Navigation",

    "press_button": "Press",
    "eject_passengers": "to eject",
    "restless_passenger": "This passenger is restless.",

    "alekiships.advancements.kayak_paddle.title": "Double Trouble",
    "alekiships.advancements.kayak_paddle.description": "Craft a Kayak Paddle",
    "alekiships.advancements.canoe.title": "Burnout Paradise",
    "alekiships.advancements.canoe.description": "Attempt to light a canoe hull",
    "alekiships.advancements.oar.title": "Oaring my Paddleboat",
    "alekiships.advancements.oar.description": "Craft an Oar",
    "alekiships.advancements.kayak.title": "I'll carry you home tonight",
    "alekiships.advancements.kayak.description": "Craft a Kayak",
    "alekiships.advancements.nav_clock.title": "Get your time from the Admiral",
    "alekiships.advancements.nav_clock.description": "Craft a Navigator's Timepiece",
    "alekiships.advancements.sextant.title": "The Stars Will Aid",
    "alekiships.advancements.sextant.description": "Craft a Sextant",
    "alekiships.advancements.barometer.title": "Surf and/or Turf",
    "alekiships.advancements.barometer.description": "Craft a Barometer",
    "alekiships.advancements.oarlock.title": "The Montlake Cut",
    "alekiships.advancements.oarlock.description": "Smith an Oarlock"
}
