from mcresources import loot_tables, ResourceManager

import constants


def structures(rm: ResourceManager):
    for wood in constants.WOODS:
        rm.loot(f"rowboat/{wood}",
                {"name": f"minecraft:{wood}_planks",
                 "functions": loot_tables.set_count(0, 16)},
                {"name": f"minecraft:{wood}_planks",
                 "functions": loot_tables.set_count(0, 16)},
                {"name": f"minecraft:{wood}_planks",
                 "functions": loot_tables.set_count(0, 16)},
                {"name": "alekiships:watercraft_frame_angled",
                 "functions": loot_tables.set_count(1, 3)},
                {"name": "alekiships:watercraft_frame_angled",
                 "functions": loot_tables.set_count(1, 3)},
                {"name": "alekiships:watercraft_frame_angled",
                 "functions": loot_tables.set_count(1)},
                {"name": "alekiships:oarlock",
                 "functions": loot_tables.set_count(0, 1)},
                {"name": "alekiships:oarlock",
                 "functions": loot_tables.set_count(0, 1)},
                {"name": "minecraft:scaffolding",
                 "functions": loot_tables.set_count(0, 5)},
                {"name": "minecraft:scaffolding",
                 "functions": loot_tables.set_count(0, 5)},
                {"name": "alekiships:oar",
                 "functions": loot_tables.set_count(0, 1)},
                {"name": "alekiships:oar",
                 "functions": loot_tables.set_count(0, 1)},
                {"name": "minecraft:lead",
                 "functions": loot_tables.set_count(0, 1)},
                path="structures",
                loot_type="chest"
                )
        rm.loot(f"sloop/{wood}",
                {"name": f"minecraft:{wood}_planks",
                 "functions": loot_tables.set_count(0, 96)},
                {"name": "alekiships:watercraft_frame_angled",
                 "functions": loot_tables.set_count(2, 6)},
                {"name": "alekiships:watercraft_frame_angled",
                 "functions": loot_tables.set_count(1)},
                {"name": "alekiships:watercraft_frame_flat",
                 "functions": loot_tables.set_count(3, 7)},
                {"name": "alekiships:cleat",
                 "functions": loot_tables.set_count(0, 4)},
                {"name": "minecraft:scaffolding",
                 "functions": loot_tables.set_count(0, 5)},
                {"name": "minecraft:slime_ball",
                 "functions": loot_tables.set_count(8)},
                {"name": "minecraft:lead",
                 "functions": loot_tables.set_count(1)},
                path="structures",
                loot_type="chest"
                )
        rm.loot(f"sloop_hut/{wood}",
                {"name": "alekiships:cleat",
                 "functions": loot_tables.set_count(0, 2)},
                {"name": "alekiships:anchor",
                 "functions": loot_tables.set_count(1)},
                {"name": "minecraft:scaffolding",
                 "functions": loot_tables.set_count(0, 10)},
                {"name": "minecraft:bread",
                 "functions": loot_tables.set_count(3, 10)},
                {"name": "alekiships:cannonball",
                 "functions": loot_tables.set_count(1, 6)},
                {"name": "minecraft:flint_and_steel",
                 "functions": loot_tables.set_count(0, 1)},
                {"name": f"minecraft:{wood}_planks",
                 "functions": loot_tables.set_count(0, 32)},
                path="structures",
                loot_type="chest"
                )
